macro[10000 ;
macro* 10 200000 ; 
macro=; 
sil = con buf ; 
xr/0 %1;
ra1;
xr+0 90 %2 2;
taxalfa * *;
sil-file;
log infile ;
set 0 root;
set 1 nchar+1;
quote '0' '1';
xr! ;
log/;
rs*;
var: n c s t;
set n %3 ;
macfloat 0 ; 
set c root / 80;
loop 1 '/.0c'
    set s getrandom[ 1 nnodes[ 0 ] ] ; 
    set t getrandom[ 1 nnodes[ 0 ] ] ; 
    set c root ; 
    edit] 0 'c' 's' 't' ;
    stop
if ( 'n' ) 
  var: i lali[ 'n' ] ;
  set n -- ;
  set * lali * ( ntax - 1 ) ;
  set * lali += ( root ) ;
  condense /0 'lali[0-'n']';
  end 
if ( %4 > 0 )
  agroup =0 0 >0 *%4 <0 0 ;
  pruntax 0 / { 0 } ;
  end 
if ( nodfork [ 0  root ] == 2 ) 
   loop (root+1) nnodes[ 0 ]
      if ( anc[ 0 #1 ] == root )
         set 0 #1 ;
         endloop ;
         end
      stop
   condense /0 '0' ; 
   end 
taxname=; 
export = cons.nw ; 
if ( argnumber > 4 )
  set 0 argnumber ; 
  if ( eqstring[ %('0') stay ] ) proc/; end
  xend 
zz


ag=0 0 >0 * %3 <0 0;
taxco-{0};
keep 0 ;
ra 1 10 3;
if ( argnumber > 3 )
  if ( !eqstring[ %4 stay ] )
    k0 ;
    if ( %4 == 2 ) ra 1 ;
    else if ( %4 == 0 ) tr ( ... ) ; 
    else ra 1 25 %4 ;
    xend
taxco +.; 
if ( nodfork [ 0  root ] == 2 ) 
   loop (root+1) nnodes[ 0 ]
      if ( anc[ 0 #1 ] == root )
         set 0 #1 ;
         endloop ;
         end
      stop
   condense /0 '0' ; 
   end 
taxname=; 
export = cons.nw ; 
if ( argnumber > 3 )
  set 0 argnumber ; 
  if ( eqstring[ %('0') stay ] ) proc/; end
  xend 
zzz
